module.exports = {
  basic: {
    'a': 'あ', 'i': 'い', 'u': 'う', 'e': 'え', 'o': 'お',
    'ka': 'か', 'ki': 'き', 'ku': 'く', 'ke': 'け', 'ko': 'こ',
    'sa': 'さ', 'shi': 'し', 'su': 'す', 'se': 'せ', 'so': 'そ',
    'ta': 'た', 'chi': 'ち', 'tsu': 'つ', 'te': 'て', 'to': 'と',
    'na': 'な', 'ni': 'に', 'nu': 'ぬ', 'ne': 'ね', 'no': 'の',
    'ha': 'は', 'hi': 'ひ', 'fu': 'ふ', 'he': 'へ', 'ho': 'ほ',
    'ma': 'ま', 'mi': 'み', 'mu': 'む', 'me': 'め', 'mo': 'も',
    'ya': 'や', 'yu': 'ゆ', 'yo': 'よ',
    'ra': 'ら', 'ri': 'り', 'ru': 'る', 're': 'れ', 'ro': 'ろ',
    'wa': 'わ', 'wo': 'を',
    'n': 'ん'
  },
  dakuten_k:  { 'ga': 'が', 'gi': 'ぎ', 'gu': 'ぐ', 'ge': 'げ', 'go': 'ご' },
  dakuten_s:  { 'za': 'ざ', 'ji': 'じ', 'zu': 'ず', 'ze': 'ぜ', 'zo': 'ぞ' },
  dakuten_t:  { 'da': 'だ', 'di': 'ぢ', 'du': 'づ', 'de': 'で', 'do': 'ど' },
  dakuten_h:  { 'ba': 'ば', 'bi': 'び', 'bu': 'ぶ', 'be': 'べ', 'bo': 'ぼ' },
  handakuten: { 'pa': 'ぱ', 'pi': 'ぴ', 'pu': 'ぷ', 'pe': 'ぺ', 'po': 'ぽ' },
  compound_k: { 'kya': 'きゃ', 'kyu': 'きゅ', 'kyo': 'きょ' },
  compound_s: { 'sha': 'しゃ', 'shu': 'しゅ', 'sho': 'しょ' },
  compound_t: { 'cha': 'ちゃ', 'chu': 'ちゅ', 'cho': 'ちょ' },
  compound_n: { 'nya': 'にゃ', 'nyu': 'にゅ', 'nyo': 'にょ' },
  compound_h: { 'hya': 'ひゃ', 'hyu': 'ひゅ', 'hyo': 'ひょ' },
  compound_m: { 'mya': 'みゃ', 'myu': 'みゅ', 'myo': 'みょ' },
  compound_r: { 'rya': 'りゃ', 'ryu': 'りゅ', 'ryo': 'りょ' },
  compound_g: { 'gya': 'ぎゃ', 'gyu': 'ぎゅ', 'gyo': 'ぎょ' },
  compound_j: { 'ja': 'じゃ', 'ju': 'じゅ', 'jo': 'じょ' },
  compound_b: { 'bya': 'びゃ', 'byu': 'びゅ', 'byo': 'びょ' },
  compound_p: { 'pya': 'ぴゃ', 'pyu': 'ぴゅ', 'pyo': 'ぴょ' },

  kata_basic: {
    'a': 'ア', 'i': 'イ', 'u': 'ウ', 'e': 'エ', 'o': 'オ',
    'ka': 'カ', 'ki': 'キ', 'ku': 'ク', 'ke': 'ケ', 'ko': 'コ',
    'sa': 'サ', 'shi': 'シ', 'su': 'ス', 'se': 'セ', 'so': 'ソ',
    'ta': 'タ', 'chi': 'チ', 'tsu': 'ツ', 'te': 'テ', 'to': 'ト',
    'na': 'ナ', 'ni': 'ニ', 'nu': 'ヌ', 'ne': 'ネ', 'no': 'ノ',
    'ha': 'ハ', 'hi': 'ヒ', 'fu': 'フ', 'he': 'ヘ', 'ho': 'ホ',
    'ma': 'マ', 'mi': 'ミ', 'mu': 'ム', 'me': 'メ', 'mo': 'モ',
    'ya': 'ヤ', 'yu': 'ユ', 'yo': 'ヨ',
    'ra': 'ラ', 'ri': 'リ', 'ru': 'ル', 're': 'レ', 'ro': 'ロ',
    'wa': 'ワ', 'wo': 'ヲ',
    'n': 'ン'
  },
  kata_dakuten_k:  { 'ga': 'ガ', 'gi': 'ギ', 'gu': 'グ', 'ge': 'ゲ', 'go': 'ゴ' },
  kata_dakuten_s:  { 'za': 'ザ', 'ji': 'ジ', 'zu': 'ズ', 'ze': 'ゼ', 'zo': 'ゾ' },
  kata_dakuten_t:  { 'da': 'ダ', 'di': 'ヂ', 'du': 'ヅ', 'de': 'デ', 'do': 'ド' },
  kata_dakuten_h:  { 'ba': 'バ', 'bi': 'ビ', 'bu': 'ブ', 'be': 'ベ', 'bo': 'ボ' },
  kata_handakuten: { 'pa': 'パ', 'pi': 'ピ', 'pu': 'プ', 'pe': 'ペ', 'po': 'ポ' },
  kata_compound_k: { 'kya': 'キャ', 'kyu': 'キュ', 'kyo': 'キョ' },
  kata_compound_s: { 'sha': 'シャ', 'shu': 'シュ', 'sho': 'ショ' },
  kata_compound_t: { 'cha': 'チャ', 'chu': 'チュ', 'cho': 'チョ' },
  kata_compound_n: { 'nya': 'ニャ', 'nyu': 'ニュ', 'nyo': 'ニョ' },
  kata_compound_h: { 'hya': 'ヒャ', 'hyu': 'ヒュ', 'hyo': 'ヒョ' },
  kata_compound_m: { 'mya': 'ミャ', 'myu': 'ミュ', 'myo': 'ミョ' },
  kata_compound_r: { 'rya': 'リャ', 'ryu': 'リュ', 'ryo': 'リョ' },
  kata_compound_g: { 'gya': 'ギャ', 'gyu': 'ギュ', 'gyo': 'ギョ' },
  kata_compound_j: { 'ja': 'ジャ', 'ju': 'ジュ', 'jo': 'ジョ' },
  kata_compound_b: { 'bya': 'ビャ', 'byu': 'ビュ', 'byo': 'ビョ' },
  kata_compound_p: { 'pya': 'ピャ', 'pyu': 'ピュ', 'pyo': 'ピョ' }
};
