module.exports = {
  basic: {
    'a': 'あ', 'i': 'い', 'u': 'う', 'e': 'え', 'o': 'お',
    'ka': 'か', 'ki': 'き', 'ku': 'く', 'ke': 'け', 'ko': 'こ',
    'sa': 'さ', 'shi': 'し', 'su': 'す', 'se': 'せ', 'so': 'そ',
    'ta': 'た', 'chi': 'ち', 'tsu': 'つ', 'te': 'て', 'to': 'と',
    'na': 'な', 'ni': 'に', 'nu': 'ぬ', 'ne': 'ね', 'no': 'の',
    'ha': 'は', 'hi': 'ひ', 'fu': 'ふ', 'he': 'へ', 'ho': 'ほ',
    'ma': 'ま', 'mi': 'み', 'mu': 'む', 'me': 'め', 'mo': 'も',
    'ya': 'や', 'yu': 'ゆ', 'yo': 'よ',
    'ra': 'ら', 'ri': 'り', 'ru': 'る', 're': 'れ', 'ro': 'ろ',
    'wa': 'わ', 'wo': 'を',
    'n': 'ん'
  },
  dakuten_k:  { 'ga': 'が', 'gi': 'ぎ', 'gu': 'ぐ', 'ge': 'げ', 'go': 'ご' },
  dakuten_s:  { 'za': 'ざ', 'ji': 'じ', 'zu': 'ず', 'ze': 'ぜ', 'zo': 'ぞ' },
  dakuten_t:  { 'da': 'だ', 'di': 'ぢ', 'du': 'づ', 'de': 'で', 'do': 'ど' },
  dakuten_h:  { 'ba': 'ば', 'bi': 'び', 'bu': 'ぶ', 'be': 'べ', 'bo': 'ぼ' },
  handakuten: { 'pa': 'ぱ', 'pi': 'ぴ', 'pu': 'ぷ', 'pe': 'ぺ', 'po': 'ぽ' },
  compound_k: { 'kya': 'きゃ', 'kyu': 'きゅ', 'kyo': 'きょ' },
  compound_s: { 'sha': 'しゃ', 'shu': 'しゅ', 'sho': 'しょ' },
  compound_t: { 'cha': 'ちゃ', 'chu': 'ちゅ', 'cho': 'ちょ' },
  compound_n: { 'nya': 'にゃ', 'nyu': 'にゅ', 'nyo': 'にょ' },
  compound_h: { 'hya': 'ひゃ', 'hyu': 'ひゅ', 'hyo': 'ひょ' },
  compound_m: { 'mya': 'みゃ', 'myu': 'みゅ', 'myo': 'みょ' },
  compound_r: { 'rya': 'りゃ', 'ryu': 'りゅ', 'ryo': 'りょ' },
  compound_g: { 'gya': 'ぎゃ', 'gyu': 'ぎゅ', 'gyo': 'ぎょ' },
  compound_j: { 'ja': 'じゃ', 'ju': 'じゅ', 'jo': 'じょ' },
  compound_b: { 'bya': 'びゃ', 'byu': 'びゅ', 'byo': 'びょ' },
  compound_p: { 'pya': 'ぴゃ', 'pyu': 'ぴゅ', 'pyo': 'ぴょ' }
};
